version: "3.9"

services:

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    environment:
      DATABASE_TYPE: postgresql
    env_file:
      - .umami.env
    depends_on:
      umami-postgres:
        condition: service_healthy
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`umami.ozeliurs.com`)"
      - "traefik.http.routers.umami.entrypoints=websecure"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"
      - "traefik.http.routers.umami.tls.certresolver=cloudflare"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3000" ]

  umami-postgres:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .umami.env
    volumes:
      - ./umami-postgres:/var/lib/postgresql/data
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]


networks:
  traefik:
    external: true